### ISSUE TITLE
PSR-0 and Composer

### ISSUE THREAD

**Issue by rdohms** [blobaugh/Meetup-API-client-for-PHP#6]
I would love to see this library be improved to use Namespaces and be organized according to the PSR-0 standard.

Also, but even more important i would love to see it in Composer, which can be done quite easily by just adding the composer.json file and listing it in Packagist.

I'm willing to help or do the complete work if its desired by the owner.

So are you ok with this? all or just composer?

**Comment by blobaugh** [comment]
PSR-0 for autoloading correct? I know the system now is pretty rudimentary, but it served my needs at the time

Could you explain a little more about Composer? There are several projects by that name. Which one are you referring to?

**Comment by rdohms** [comment]
Check out http://getcomposer.org or my slides on http://slideshare.com/rdohms . We can
chat on irc later also.

**Comment by rdohms** [comment]
Composer is a Dependecy Manager, a new and improved solution compared to PEAR. Its took off in the Symfony community and has been growing since. I already have the initial work on it done, i'll send a PR later on.

As for PSR-0 and namespaces, yes it is for autoading, but its also a stadard defined by the frameworks, so that makes your library easier to fit in other apps, i can understand the current structure and how it came to be, but i think it is mature enough for us to alter it a bit and get it organized, especially for future additions.

I'm going to look at it and propose a namespace structure later to see if you agree. Also tests :P

**Comment by blobaugh** [comment]
Oh sorry, for some reason I was not pinged when you posted another comment. Thanks for checking into this. The main thing that I want to ensure continues to happen going forward is excellent documentation. Any changes you make that involve a new way to do things please update in the wiki
